### ISSUE TITLE
0.14.0 release breaks semantic versioning

### ISSUE THREAD

**Issue by aholmes** [alecthomas/flask_injector#76]
Hi,

First, this issue assumes this repository's releases follow semantic versioning. If not, I ask to consider doing so.

Regarding 812168f057702b4e86bb0328fd3760ff0ada3ae8, the change to require Flask 2.1.2 is a breaking change. Semantic versioning calls for a "major" version number increment when this occurs. This matters for automation pipelines, notably (given this is GitHub) Dependabot may attempt to update to this version when it should not. For a fix, I'm asking to "yank" version 0.14.0 and release a new major version instead.

**Comment by jstasiak** [comment]
Hey,

I'm sorry that this created issues for you.


Seeing how the version bump follows an already established (although undocumented) versioning scheme, there's no promise to follow semantic versioning *and* the breaking change is explicitly documented I'll close this issue.

Somewhat ironically this version bump is still kind of consistent with semantic versioning anyway, because we're using major version zero and

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

(granted, the library is no longer in "initial development")
